### ISSUE TITLE
No Permission problem

### ISSUE THREAD

**Issue by mellobob** [sole/aafm#41]
I'm running aafm on a Galaxy tab 2.0 7".

If I try to copy a file to the installed sd card I get the following:

EXECUTE= adb shell ls -l -a /mnt/extSdCard/Music/
EXECUTE= adb push "/home/bob/Music/jazz-collections/25 Jazz Greats/25 Jazz Greats Vol 1/.02_count_basie__lets_jump.mood" /mnt/extSdCard/Music
failed to copy '/home/bob/Music/jazz-collections/25 Jazz Greats/25 Jazz Greats Vol 1/.02_count_basie__lets_jump.mood' to '/mnt/extSdCard/Music/.02_count_basie__lets_jump.mood': Permission denied

Using main memory seems to work fine.

Also, can I copy entire directory trees, or just one file at  a time?

Thanks!

**Comment by sole** [comment]
It might be something to do with your device and the memory or I don't-know-what O:-)
All these device variations make my head dizzy!

Can you write to that card with another program?

You can copy directories too as you do files. The only thing is that it will look as it is 'frozen', because it's not updating per file but per directory. So until it's done it won't update. But you can see in the log that it is doing stuff.
This is something I have in the list of improvements, see #24.
